### ISSUE TITLE
홈페이지 디자인 조사

### ISSUE THREAD

**Issue by wonderino** [jaryogujo/jaryogujo.github.io#1]

**Comment by leejeonghoon** [comment]
## 기본 삽입정보
- ![logo](https://c2.staticflickr.com/6/5706/22871475381_a178797599_o.png) 
- one page navigation menu
  - home/about
    - 이모저모를 요래조래 화면에 보이게 합니다
  - portfolio(projects)
    - 감독으로 보는 한국프로야구 역사
      - 한국프로야구 개막 원년부터 작년 2014년까지의 역사를 감독을 중심으로 알아보았다.득점 및 실점 관련 기록을 바탕으로 시즌별 구단의 공격력과 수비력을 평가하고 이를 바탕으로 프로야구 전체 역사를 시각화 하였다.
        - ![](https://c1.staticflickr.com/1/741/22860246605_e3f13cb102_h.jpg)
      - [시각화](http://kbo-history.jaryogujo.io/)
      - [제작기](http://blog.jaryogujo.io/kbo-vis-blog/)
  - contact us
- sns
  - [facebook](http://facebook.com/jaryogujo)

**Comment by leejeonghoon** [comment]
## 01 네비게이션 / 홈
- one page
- navigation menu
  - home
  - about
  - portfolio
  - contact
- 풀스크린, centered navigation
- learn more / ↓ 버튼
- 텍스트: infovis lab/team/group?등의 내용
- 배경: 그라디언트or이미지
- reference
  - http://sparkhouselabs.com/#welcome
  - https://www.mapbox.com/data-platform/
  - https://walkinsights.com/

![image](https://cloud.githubusercontent.com/assets/10662388/11018520/c8a46ce0-860f-11e5-9ee3-92c3ca28e898.png)

## 02 about
- 텍스트: 이모저모를 요래조래 화면에 보이게 합니다. +@

## 03 portfolio (projects)
- 감독으로 보는 한국프로야구 역사
  - 한국프로야구 개막 원년부터 작년 2014년까지의 역사를 감독을 중심으로 알아보았다.득점 및 실점 관련 기록을 바탕으로 시즌별 구단의 공격력과 수비력을 평가하고 이를 바탕으로 프로야구 전체 역사를 시각화 하였다.
    - 시각화, 제작기 버튼
- A 
  ![image](https://cloud.githubusercontent.com/assets/10662388/11018529/89e60666-8610-11e5-9303-7879ef5fd519.png)
- B 그림 배치해봤는데 안어울리면 아래 레이아웃으로

![image](https://cloud.githubusercontent.com/assets/10662388/11018532/c64b7c4e-8610-11e5-9403-761c29486ff3.png)
- 확장은 

![image](https://cloud.githubusercontent.com/assets/10662388/11018533/cd368314-8610-11e5-8381-4bf3e27b0d08.png)

## 04 contact

## 05 footer
- 딱히 내용이 많이 없으므로 그냥 슬림하게
